2024-11-15 00:11:22 - INFO - Запуск бота...
2024-11-15 00:11:22 - INFO - База данных инициализирована
2024-11-15 00:11:22 - INFO - AuthHandler инициализирован
2024-11-15 00:11:23 - INFO - Приложение создано с токеном: 7892353308...
2024-11-15 00:11:23 - INFO - Добавление обработчика конверсации
2024-11-15 00:11:23 - INFO - Запуск процесса поллинга
2024-11-15 00:11:23 - DEBUG - Вызвана команда start пользователем 5104161932
2024-11-15 00:11:23 - DEBUG - Отправлено стартовое меню
2024-11-15 00:11:23 - DEBUG - Вызвана команда start пользователем 5104161932
2024-11-15 00:11:24 - DEBUG - Отправлено стартовое меню
2024-11-15 00:11:24 - DEBUG - Вызвана команда start пользователем 5104161932
2024-11-15 00:11:24 - DEBUG - Отправлено стартовое меню
2024-11-15 00:11:26 - DEBUG - Начало регистрации для пользователя 5104161932
2024-11-15 00:11:27 - DEBUG - Получено ФИО: ↩️ Назад
2024-11-15 00:11:27 - DEBUG - Вызвана команда start пользователем 5104161932
2024-11-15 00:11:27 - DEBUG - Отправлено стартовое меню
2024-11-15 00:11:28 - ERROR - Произошла ошибка: name 'resize_keyboard' is not defined
2024-11-15 00:11:28 - ERROR - name 'resize_keyboard' is not defined
Traceback (most recent call last):
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 1319, in process_update
    await coroutine
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 844, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        update, application, handler_check_result, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anxiety\.cursor-tutor\handlers\auth_handler.py", line 256, in authorize
    reply_keyboard = ([['↩️ Назад']], resize_keyboard==True)
                                      ^^^^^^^^^^^^^^^
NameError: name 'resize_keyboard' is not defined
2024-11-15 00:11:28 - DEBUG - Вызвана команда start пользователем 6121074409
2024-11-15 00:11:28 - DEBUG - Отправлено стартовое меню
2024-11-15 00:11:29 - ERROR - Произошла ошибка: name 'resize_keyboard' is not defined
2024-11-15 00:11:29 - ERROR - name 'resize_keyboard' is not defined
Traceback (most recent call last):
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 1319, in process_update
    await coroutine
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 844, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        update, application, handler_check_result, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anxiety\.cursor-tutor\handlers\auth_handler.py", line 256, in authorize
    reply_keyboard = ([['↩️ Назад']], resize_keyboard==True)
                                      ^^^^^^^^^^^^^^^
NameError: name 'resize_keyboard' is not defined
2024-11-15 00:11:45 - ERROR - Произошла ошибка: name 'resize_keyboard' is not defined
2024-11-15 00:11:45 - ERROR - name 'resize_keyboard' is not defined
Traceback (most recent call last):
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 1319, in process_update
    await coroutine
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 844, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        update, application, handler_check_result, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anxiety\.cursor-tutor\handlers\auth_handler.py", line 256, in authorize
    reply_keyboard = ([['↩️ Назад']], resize_keyboard==True)
                                      ^^^^^^^^^^^^^^^
NameError: name 'resize_keyboard' is not defined
2024-11-15 00:11:46 - DEBUG - Начало регистрации для пользователя 5104161932
2024-11-15 00:11:47 - DEBUG - Получено ФИО: ↩️ Назад
2024-11-15 00:11:47 - DEBUG - Вызвана команда start пользователем 5104161932
2024-11-15 00:11:48 - DEBUG - Отправлено стартовое меню
2024-11-15 00:11:49 - ERROR - Произошла ошибка: name 'resize_keyboard' is not defined
2024-11-15 00:11:49 - ERROR - name 'resize_keyboard' is not defined
Traceback (most recent call last):
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 1319, in process_update
    await coroutine
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 844, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        update, application, handler_check_result, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anxiety\.cursor-tutor\handlers\auth_handler.py", line 256, in authorize
    reply_keyboard = ([['↩️ Назад']], resize_keyboard==True)
                                      ^^^^^^^^^^^^^^^
NameError: name 'resize_keyboard' is not defined
2024-11-15 00:11:50 - ERROR - Произошла ошибка: name 'resize_keyboard' is not defined
2024-11-15 00:11:50 - ERROR - name 'resize_keyboard' is not defined
Traceback (most recent call last):
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 1319, in process_update
    await coroutine
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 844, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        update, application, handler_check_result, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anxiety\.cursor-tutor\handlers\auth_handler.py", line 256, in authorize
    reply_keyboard = ([['↩️ Назад']], resize_keyboard==True)
                                      ^^^^^^^^^^^^^^^
NameError: name 'resize_keyboard' is not defined
2024-11-15 00:13:42 - INFO - Бот остановлен пользователем
